name: ava-sdk-test
services:
  aggregator:
    image: avaprotocol/avs-dev:${DOCKER_IMAGE_TAG:-latest} # DOCKER_IMAGE_TAG is a specific git commit hash of https://github.com/AvaProtocol/EigenLayer-AVS. It’s used in the .github/workflows/dev-test-on-pr.yml file.
    command:
      - "aggregator"
    ports:
      - "2206:2206"
      - "1323:1323"
    volumes:
      - ./config:/app/config
