name: ava-sdk-test
services:
  aggregator:
    image: avaprotocol/avs-dev:${DOCKER_IMAGE_TAG:-latest} # DOCKER_IMAGE_TAG is a specific git commit hash of https://github.com/AvaProtocol/EigenLayer-AVS. It's used in the .github/workflows/dev-test-on-pr.yml file.
    command:
      - "aggregator"
      - "--config"
      - "/app/config/aggregator.runtime.yaml"
    ports:
      - "2206:2206"
      - "1323:1323"
    volumes:
      - ./config:/app/config
    healthcheck:
      test: ["CMD-SHELL", "echo -e 'GET /up HTTP/1.0\\r\\nHost: localhost\\r\\n\\r\\n' | socat - TCP:localhost:1323 | grep -q '200 OK'"]
      interval: 5s
      retries: 24
      start_period: 60s
      timeout: 5s

  operator:
    image: avaprotocol/avs-dev:${DOCKER_IMAGE_TAG:-latest}
    command:
      - "operator"
      - "--config"
      - "/app/config/operator.runtime.yaml"
    ports:
      - "9010:9010"
    volumes:
      - ./config:/app/config
    depends_on:
      aggregator:
        condition: service_healthy
