name: ava-sdk-test
services:
  aggregator:
    image: avaprotocol/avs-dev:${DOCKER_IMAGE_TAG:-latest} # DOCKER_IMAGE_TAG is a specific git commit hash of https://github.com/AvaProtocol/EigenLayer-AVS. It's used in the .github/workflows/dev-test-on-pr.yml file.
    command:
      - "aggregator"
      - "--config"
      - "/app/config/aggregator.runtime.yaml"
    ports:
      - "2206:2206"
      - "1323:1323"
    volumes:
      - ./config:/app/config
    healthcheck:
      test: curl --fail http://localhost:1323/up || exit 1
      interval: 5s
      retries: 24
      start_period: 5s
      timeout: 5s

  operator:
    image: avaprotocol/avs-dev:${DOCKER_IMAGE_TAG:-latest}
    command:
      - "operator"
      - "--config"
      - "/app/config/operator.runtime.yaml"
    ports:
      - "9010:9010"
    volumes:
      - ./config:/app/config
    depends_on:
      aggregator:
        condition: service_healthy
