environment: development
db_path: /tmp/ap-avs/db-${TEST_ENV}

# Runtime-generated config - secrets injected from GitHub environment
ecdsa_private_key: ${ECDSA_PRIVATE_KEY}

eth_rpc_url: https://${CHAIN_ENDPOINT}
eth_ws_url: wss://${CHAIN_ENDPOINT}

rpc_bind_address: "0.0.0.0:2206"
http_bind_address: "0.0.0.0:1323"

avs_registry_coordinator_address: 0xcA95381802FD1398d5BF2D01243210cFb3a2b3BD
operator_state_retriever_address: 0x070E0ABE8407eb4727fC7C5284bdc1e5E5CBf605

jwt_secret: ${JWT_SECRET}

# Optional services configuration
server_name: "aggregator-${TEST_ENV}-ci"
sentry_dsn: ${SENTRY_DSN}

# account abstraction config
# Sepolia
smart_wallet:
  eth_rpc_url: https://${CHAIN_ENDPOINT}
  eth_ws_url: wss://${CHAIN_ENDPOINT}
  bundler_url: ${BUNDLER_URL}

  controller_private_key: ${CONTROLLER_PRIVATE_KEY}
  max_wallets_per_owner: 2000

# Optional services - will use environment variables if available
tenderly_account: ${TENDERLY_ACCOUNT}
tenderly_project: ${TENDERLY_PROJECT}
tenderly_access_key: ${TENDERLY_ACCESS_KEY}

macros:
  secrets:
    ap_notify_bot_token: ${AP_NOTIFY_BOT_TOKEN}
    sendgrid_key: ${SENDGRID_KEY}
    thegraph_api_key: ${THEGRAPH_API_KEY}
    moralis_api_key: ${MORALIS_API_KEY}
