name: Release with Changeset

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Commit Changeset Version Bump
        id: changesets
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx changeset version

          # Print the git status to see the changes
          git status

          if [ -n "$(git status --porcelain)" ]; then
            NEW_VERSION=$(node -p "require('./package.json').version")
            git add .
            git commit -m "Version packages"
            echo "commit=true" >> $GITHUB_ENV
            echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
            echo "::set-output name=commit::true"
          else
            echo "No changes to commit"
            echo "commit=false" >> $GITHUB_ENV
            echo "::set-output name=commit::false"
          fi

      - name: Create Version Bump Branch and Push
        if: steps.changesets.outputs.commit == 'true'
        run: |
          BRANCH_NAME="bump-to-${{ env.NEW_VERSION }}"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          BRANCH_NAME: bump-to-${{ env.NEW_VERSION }}

      - name: Verify Changes Before PR
        if: steps.changesets.outputs.commit == 'true'
        run: |
          git fetch origin
          git diff --exit-code origin/main || echo "Changes detected"

      - name: Open Pull Request for Version Bump
        if: steps.changesets.outputs.commit == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          base: main
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: true
          title: "Version packages"
          body: "This pull request contains version bumps for packages."

      - name: Check Version Change
        id: version_check
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          LATEST_RELEASE=$(gh release list --limit 1 | cut -f1)
          LATEST_VERSION=${LATEST_RELEASE#v}

          echo "Current version: ${CURRENT_VERSION}"
          echo "Latest release: ${LATEST_VERSION}"

          if [ "$(printf '%s\n' "$LATEST_VERSION" "$CURRENT_VERSION" | sort -V | tail -n1)" = "$CURRENT_VERSION" ] && [ "$LATEST_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Version increment detected"
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "No version increment detected or versions are equal"
            echo "should_release=false" >> $GITHUB_OUTPUT
            exit 0
          fi

      - name: Create GitHub Release
        if: steps.version_check.outputs.should_release == 'true'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          gh release create "v${CURRENT_VERSION}" \
            --title "v${CURRENT_VERSION}" \
            --generate-notes
