name: PR Changeset

on:
  push:
    branches:
      - main

jobs:
  changeset:
    name: Run Changeset
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          # Add these lines to fetch all branches
          fetch-tags: true

      - name: Fetch main branch
        run: |
          git fetch origin main
          git merge-base --is-ancestor origin/main HEAD || echo "Main branch is ahead"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20"

      - name: Install dependencies
        run: npm ci

      - name: Run Changeset
        run: |
          PR_TITLE=$(echo "${{ github.event.pull_request.title }}" | tr -d '"\\')
          echo "Setting changeset summary to the title of PR: ${PR_TITLE}"
          npx changeset add --empty --message "${PR_TITLE}" --type "patch"

      # Examine the changes generated by Changeset
      - name: Review Changeset Files
        run: |
          echo "Checking if there's new code changes in the .changeset folder"
          find .changeset -type f -not -name "config.json" -not -name "README.md" -exec ls -l {} +

      - name: Commit and push changes
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .changeset
          git commit -m "Add changeset: ${COMMIT_MSG}" || echo "No changes to commit"
          git push
