name: Record Changeset

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Change type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: "patch"

jobs:
  changeset:
    name: Create Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Check if on main branch
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          if [ "$CURRENT_BRANCH" = "main" ]; then
            echo "Error: Cannot create changeset on main branch"
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Create Changeset
        id: changeset
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Creating changeset for: ${COMMIT_MESSAGE}"

          # Create the changeset file first
          CHANGESET_OUTPUT=$(npx changeset add --empty)
          
          # Get the generated changeset filename
          CHANGESET_FILE=$(echo "$CHANGESET_OUTPUT" | grep -o '[a-z0-9\-]\+\.md')
          
          # Modify the changeset file to include the package
          echo "---
          '@avaprotocol/sdk-js': ${{ github.event.inputs.version_type }}
          ---

          ${COMMIT_MESSAGE}" > .changeset/${CHANGESET_FILE}

          # Verify changeset creation
          if [ ! -d ".changeset" ]; then
            echo "Error: .changeset directory not created"
            exit 1
          fi

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: ${{ env.commit_message }}
        run: |
          # Create PR from current branch
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          gh pr create \
            --title "Add changeset for ${COMMIT_MESSAGE}" \
            --body "This pull request adds a changeset for ${COMMIT_MESSAGE}. Please review." \
            --base main \
            --head "$CURRENT_BRANCH"

    permissions:
      contents: write
      pull-requests: write
