name: Run tests against staging on PR

on:
  pull_request:
    branches: [main]

jobs:
  staging-test:
    runs-on: ubuntu-latest
    environment: test # The below environment variables are only available in the test environment

    env:
      TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
      TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
      ENDPOINT: ${{ vars.ENDPOINT }}
      CHAIN_ENDPOINT: ${{ secrets.CHAIN_ENDPOINT }}
      # On staging env, when test run it may not cleanup data properly for multiple reasons.
      # In the next run, especially on pagination test, the assumption about data is wrong.
      # For those kind of particular test, we want to ensure a 100% unique salt across run
      # One way to do so, is get this run_id from github action and use it as salt
      # On local dev, we just default to a hard code number in the test to isolate its. data
      # on local test is continously wipe out on every run so it isn't a problem like staging
      # We may want to sweep and delete task data on those test account
      RUN_ID: ${{ github.run_id }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0 # Fetch all history for all branches

      - name: Debug environment variables
        run: |
          echo "ENDPOINT: $ENDPOINT"

      - name: Check Source or Test Code Changes
        id: check_source_changes
        run: |
          echo "=== Pull Request Information ==="
          echo "PR Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "PR Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "PR Head Ref: ${{ github.event.pull_request.head.ref }}"
          echo "GitHub Ref: ${{ github.ref }}"
          echo "Base Branch: ${{ github.base_ref }}"

          # Fetch both branches
          git fetch origin ${{ github.base_ref }}
          git fetch origin ${{ github.event.pull_request.head.ref }}

          # Get all changed files (only names)
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} HEAD)

          # Define the source code patterns we want to monitor
          SOURCE_PATTERN='^(packages/sdk-js/src|packages/types/src|tests)'

          echo "=== Git Information ==="
          echo "Current branch: $(git branch --show-current)"
          echo "Git status:"
          git status

          echo "=== Changed Files ==="
          echo "$CHANGED_FILES"

          # Check if any files in our monitored directories have changed
          MATCHING_FILES=$(echo "$CHANGED_FILES" | grep -E "$SOURCE_PATTERN" || echo "")

          echo "=== Matching Files ==="
          echo "$MATCHING_FILES"

          if [ -z "$MATCHING_FILES" ]; then
            echo "source_changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in monitored directories, skipping tests"
          else
            echo "source_changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in monitored directories:"
            echo "$MATCHING_FILES"
          fi
        shell: bash

      - name: Use Node.js
        if: steps.check_source_changes.outputs.source_changed == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn install

      - name: Build
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn build

      - name: Test Authentication
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:auth

      - name: Test Create Workflow
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:createWorkflow

      - name: Test Get Workflow
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:getWorkflow

      - name: Test Get Workflows
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:getWorkflows

      - name: Test Cancel Workflow
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:cancelWorkflow

      - name: Test Delete Workflow
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:deleteWorkflow

      - name: Test Get Executions
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:getExecutions

      - name: Test Get Wallet
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:getWallet

      - name: Test Get Wallets
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:getWallets

      - name: Test Secret
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:secret

      - name: Test Step
        if: steps.check_source_changes.outputs.source_changed == 'true'
        run: yarn test:step
