name: Test Steps

on:
  workflow_call:
    inputs:
      test_env:
        required: true
        type: string
    secrets:
      TEST_PRIVATE_KEY:
        required: true
      CHAIN_ENDPOINT:
        required: true
      AVS_API_KEY:
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment: ${{ inputs.test_env }}
    continue-on-error: true
    strategy:
      matrix:
        test:
          [
            "auth",
            "createWorkflow",
            "getWorkflow",
            "getWorkflows",
            "cancelWorkflow",
            "deleteWorkflow",
            "triggerWorkflow",
            "getExecutions",
            "getWallet",
            "getWallets",
            "secret",
          ]

    env:
      CHAIN_ENDPOINT: ${{ secrets.CHAIN_ENDPOINT }}
      ENDPOINT: "localhost:2206"
      TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
      AVS_API_KEY: ${{ secrets.AVS_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Print Test Environment Variables
        run: |
          echo "=== Required Variables from envalid.ts ==="
          echo "AVS_API_KEY: ...${{ secrets.AVS_API_KEY }}"
          echo "CHAIN_ENDPOINT: ${{ secrets.CHAIN_ENDPOINT }}"
          echo "TEST_PRIVATE_KEY: ...${{ secrets.TEST_PRIVATE_KEY }}"
          echo "TEST_ENV: ${{ inputs.test_env }}"
          echo "avsEndpoint: $ENDPOINT"
          echo "chainId: 11155111"
          echo "factoryAddress: 0xB99BC2E399e06CddCF5E725c0ea341E8f0322834"

      - name: Run Test
        run: yarn test:${{ matrix.test }}
