name: Changeset Version Bump

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Version bump type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: "patch"

jobs:
  changeset:
    name: Run Changeset
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch main branch
        run: |
          git fetch origin main
          git merge-base --is-ancestor origin/main HEAD || echo "Main branch is ahead"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20"

      - name: Install dependencies
        run: npm ci

      - name: Run Changeset
        env:
          VERSION_TYPE: ${{ github.event.inputs.version_type }}
        run: npm run changeset

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .changeset package.json
          git commit -m "Version bump via changeset" || echo "No changes to commit"
          git push --follow-tags
