name: Changeset Version Bump

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version bump type'
        required: true
        type: choice
        options:
        - patch
        - minor
        - major
        default: 'patch'

jobs:
  changeset:
    name: Run Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch main branch
        run: |
          git fetch origin main
          git merge-base --is-ancestor origin/main HEAD || echo "Main branch is ahead"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20"

      - name: Install dependencies
        run: npm ci

      - name: Run Changeset
        id: changeset
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          # Get and log current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: ${CURRENT_VERSION}"
          
          # Create a temporary changeset file directly
          echo "---
'ava-sdk-js': ${{ github.event.inputs.version_type }}
---

${COMMIT_MESSAGE}" > .changeset/version-bump.md
          
          # Run changeset version to bump the version
          npx changeset version
          
          # Get and log new version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "New version: ${NEW_VERSION}"
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      # Examine the changes generated by Changeset
      - name: Review Changeset Files
        run: |
          echo "Checking if there's new code changes in the .changeset folder"
          find .changeset -type f -not -name "config.json" -not -name "README.md" -exec ls -l {} +

      - name: Commit and push changes
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .changeset package.json
          git commit -m "Version bump to ${{ steps.changeset.outputs.new_version }}: ${COMMIT_MSG}" || echo "No changes to commit"
          git push
