name: Record Changeset

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Change type"
        required: true
        type: choice
        options:
          - patch
          - minor
          - major
        default: "patch"

jobs:
  changeset:
    name: Create Changeset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch main branch
        run: |
          git fetch origin main
          git merge-base --is-ancestor origin/main HEAD || echo "Main branch is ahead"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.20"

      - name: Install dependencies
        run: npm ci

      - name: Create Changeset
        id: changeset
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "Creating changeset for: ${COMMIT_MESSAGE}"

          # Create changeset and capture the output
          npx changeset add --empty --message "${COMMIT_MESSAGE}" --type "${{ github.event.inputs.version_type }}"
          
          # Verify changeset creation
          if [ ! -d ".changeset" ]; then
            echo "Error: .changeset directory not created"
            exit 1
          fi

      - name: Commit and push changes
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "chore: add changeset for ${COMMIT_MSG}" || echo "No changes to commit"
          git push

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: add changeset"
          title: "Add changeset for changes"
          body: |
            Automated changeset creation via GitHub Actions
            Original commit message: ${{ github.event.inputs.commit_message }}
          branch: changeset/add-changes
          base: main
          delete-branch: true
    permissions:
      contents: write
      pull-requests: write
